module Survey
  # Static ISO 3166-1 country list (English, pre-sorted) + Kosovo (user-assigned XK).
  # Bundled statically on purpose so the list never depends on the host's ICU data.
  module Countries
    Country = Data.define(:code, :label)

    ALL = [
      Country.new(code: "af", label: "Afghanistan"),
      Country.new(code: "ax", label: "Åland Islands"),
      Country.new(code: "al", label: "Albania"),
      Country.new(code: "dz", label: "Algeria"),
      Country.new(code: "as", label: "American Samoa"),
      Country.new(code: "ad", label: "Andorra"),
      Country.new(code: "ao", label: "Angola"),
      Country.new(code: "ai", label: "Anguilla"),
      Country.new(code: "aq", label: "Antarctica"),
      Country.new(code: "ag", label: "Antigua & Barbuda"),
      Country.new(code: "ar", label: "Argentina"),
      Country.new(code: "am", label: "Armenia"),
      Country.new(code: "aw", label: "Aruba"),
      Country.new(code: "au", label: "Australia"),
      Country.new(code: "at", label: "Austria"),
      Country.new(code: "az", label: "Azerbaijan"),
      Country.new(code: "bs", label: "Bahamas"),
      Country.new(code: "bh", label: "Bahrain"),
      Country.new(code: "bd", label: "Bangladesh"),
      Country.new(code: "bb", label: "Barbados"),
      Country.new(code: "by", label: "Belarus"),
      Country.new(code: "be", label: "Belgium"),
      Country.new(code: "bz", label: "Belize"),
      Country.new(code: "bj", label: "Benin"),
      Country.new(code: "bm", label: "Bermuda"),
      Country.new(code: "bt", label: "Bhutan"),
      Country.new(code: "bo", label: "Bolivia"),
      Country.new(code: "ba", label: "Bosnia & Herzegovina"),
      Country.new(code: "bw", label: "Botswana"),
      Country.new(code: "bv", label: "Bouvet Island"),
      Country.new(code: "br", label: "Brazil"),
      Country.new(code: "io", label: "British Indian Ocean Territory"),
      Country.new(code: "vg", label: "British Virgin Islands"),
      Country.new(code: "bn", label: "Brunei"),
      Country.new(code: "bg", label: "Bulgaria"),
      Country.new(code: "bf", label: "Burkina Faso"),
      Country.new(code: "bi", label: "Burundi"),
      Country.new(code: "kh", label: "Cambodia"),
      Country.new(code: "cm", label: "Cameroon"),
      Country.new(code: "ca", label: "Canada"),
      Country.new(code: "cv", label: "Cape Verde"),
      Country.new(code: "bq", label: "Caribbean Netherlands"),
      Country.new(code: "ky", label: "Cayman Islands"),
      Country.new(code: "cf", label: "Central African Republic"),
      Country.new(code: "td", label: "Chad"),
      Country.new(code: "cl", label: "Chile"),
      Country.new(code: "cn", label: "China"),
      Country.new(code: "cx", label: "Christmas Island"),
      Country.new(code: "cc", label: "Cocos (Keeling) Islands"),
      Country.new(code: "co", label: "Colombia"),
      Country.new(code: "km", label: "Comoros"),
      Country.new(code: "cg", label: "Congo - Brazzaville"),
      Country.new(code: "cd", label: "Congo - Kinshasa"),
      Country.new(code: "ck", label: "Cook Islands"),
      Country.new(code: "cr", label: "Costa Rica"),
      Country.new(code: "ci", label: "Côte d’Ivoire"),
      Country.new(code: "hr", label: "Croatia"),
      Country.new(code: "cu", label: "Cuba"),
      Country.new(code: "cw", label: "Curaçao"),
      Country.new(code: "cy", label: "Cyprus"),
      Country.new(code: "cz", label: "Czechia"),
      Country.new(code: "dk", label: "Denmark"),
      Country.new(code: "dj", label: "Djibouti"),
      Country.new(code: "dm", label: "Dominica"),
      Country.new(code: "do", label: "Dominican Republic"),
      Country.new(code: "ec", label: "Ecuador"),
      Country.new(code: "eg", label: "Egypt"),
      Country.new(code: "sv", label: "El Salvador"),
      Country.new(code: "gq", label: "Equatorial Guinea"),
      Country.new(code: "er", label: "Eritrea"),
      Country.new(code: "ee", label: "Estonia"),
      Country.new(code: "sz", label: "Eswatini"),
      Country.new(code: "et", label: "Ethiopia"),
      Country.new(code: "fk", label: "Falkland Islands"),
      Country.new(code: "fo", label: "Faroe Islands"),
      Country.new(code: "fj", label: "Fiji"),
      Country.new(code: "fi", label: "Finland"),
      Country.new(code: "fr", label: "France"),
      Country.new(code: "gf", label: "French Guiana"),
      Country.new(code: "pf", label: "French Polynesia"),
      Country.new(code: "tf", label: "French Southern Territories"),
      Country.new(code: "ga", label: "Gabon"),
      Country.new(code: "gm", label: "Gambia"),
      Country.new(code: "ge", label: "Georgia"),
      Country.new(code: "de", label: "Germany"),
      Country.new(code: "gh", label: "Ghana"),
      Country.new(code: "gi", label: "Gibraltar"),
      Country.new(code: "gr", label: "Greece"),
      Country.new(code: "gl", label: "Greenland"),
      Country.new(code: "gd", label: "Grenada"),
      Country.new(code: "gp", label: "Guadeloupe"),
      Country.new(code: "gu", label: "Guam"),
      Country.new(code: "gt", label: "Guatemala"),
      Country.new(code: "gg", label: "Guernsey"),
      Country.new(code: "gn", label: "Guinea"),
      Country.new(code: "gw", label: "Guinea-Bissau"),
      Country.new(code: "gy", label: "Guyana"),
      Country.new(code: "ht", label: "Haiti"),
      Country.new(code: "hm", label: "Heard & McDonald Islands"),
      Country.new(code: "hn", label: "Honduras"),
      Country.new(code: "hk", label: "Hong Kong SAR China"),
      Country.new(code: "hu", label: "Hungary"),
      Country.new(code: "is", label: "Iceland"),
      Country.new(code: "in", label: "India"),
      Country.new(code: "id", label: "Indonesia"),
      Country.new(code: "ir", label: "Iran"),
      Country.new(code: "iq", label: "Iraq"),
      Country.new(code: "ie", label: "Ireland"),
      Country.new(code: "im", label: "Isle of Man"),
      Country.new(code: "il", label: "Israel"),
      Country.new(code: "it", label: "Italy"),
      Country.new(code: "jm", label: "Jamaica"),
      Country.new(code: "jp", label: "Japan"),
      Country.new(code: "je", label: "Jersey"),
      Country.new(code: "jo", label: "Jordan"),
      Country.new(code: "kz", label: "Kazakhstan"),
      Country.new(code: "ke", label: "Kenya"),
      Country.new(code: "ki", label: "Kiribati"),
      Country.new(code: "xk", label: "Kosovo"),
      Country.new(code: "kw", label: "Kuwait"),
      Country.new(code: "kg", label: "Kyrgyzstan"),
      Country.new(code: "la", label: "Laos"),
      Country.new(code: "lv", label: "Latvia"),
      Country.new(code: "lb", label: "Lebanon"),
      Country.new(code: "ls", label: "Lesotho"),
      Country.new(code: "lr", label: "Liberia"),
      Country.new(code: "ly", label: "Libya"),
      Country.new(code: "li", label: "Liechtenstein"),
      Country.new(code: "lt", label: "Lithuania"),
      Country.new(code: "lu", label: "Luxembourg"),
      Country.new(code: "mo", label: "Macao SAR China"),
      Country.new(code: "mg", label: "Madagascar"),
      Country.new(code: "mw", label: "Malawi"),
      Country.new(code: "my", label: "Malaysia"),
      Country.new(code: "mv", label: "Maldives"),
      Country.new(code: "ml", label: "Mali"),
      Country.new(code: "mt", label: "Malta"),
      Country.new(code: "mh", label: "Marshall Islands"),
      Country.new(code: "mq", label: "Martinique"),
      Country.new(code: "mr", label: "Mauritania"),
      Country.new(code: "mu", label: "Mauritius"),
      Country.new(code: "yt", label: "Mayotte"),
      Country.new(code: "mx", label: "Mexico"),
      Country.new(code: "fm", label: "Micronesia"),
      Country.new(code: "md", label: "Moldova"),
      Country.new(code: "mc", label: "Monaco"),
      Country.new(code: "mn", label: "Mongolia"),
      Country.new(code: "me", label: "Montenegro"),
      Country.new(code: "ms", label: "Montserrat"),
      Country.new(code: "ma", label: "Morocco"),
      Country.new(code: "mz", label: "Mozambique"),
      Country.new(code: "mm", label: "Myanmar (Burma)"),
      Country.new(code: "na", label: "Namibia"),
      Country.new(code: "nr", label: "Nauru"),
      Country.new(code: "np", label: "Nepal"),
      Country.new(code: "nl", label: "Netherlands"),
      Country.new(code: "nc", label: "New Caledonia"),
      Country.new(code: "nz", label: "New Zealand"),
      Country.new(code: "ni", label: "Nicaragua"),
      Country.new(code: "ne", label: "Niger"),
      Country.new(code: "ng", label: "Nigeria"),
      Country.new(code: "nu", label: "Niue"),
      Country.new(code: "nf", label: "Norfolk Island"),
      Country.new(code: "kp", label: "North Korea"),
      Country.new(code: "mk", label: "North Macedonia"),
      Country.new(code: "mp", label: "Northern Mariana Islands"),
      Country.new(code: "no", label: "Norway"),
      Country.new(code: "om", label: "Oman"),
      Country.new(code: "pk", label: "Pakistan"),
      Country.new(code: "pw", label: "Palau"),
      Country.new(code: "ps", label: "Palestinian Territories"),
      Country.new(code: "pa", label: "Panama"),
      Country.new(code: "pg", label: "Papua New Guinea"),
      Country.new(code: "py", label: "Paraguay"),
      Country.new(code: "pe", label: "Peru"),
      Country.new(code: "ph", label: "Philippines"),
      Country.new(code: "pn", label: "Pitcairn Islands"),
      Country.new(code: "pl", label: "Poland"),
      Country.new(code: "pt", label: "Portugal"),
      Country.new(code: "pr", label: "Puerto Rico"),
      Country.new(code: "qa", label: "Qatar"),
      Country.new(code: "re", label: "Réunion"),
      Country.new(code: "ro", label: "Romania"),
      Country.new(code: "ru", label: "Russia"),
      Country.new(code: "rw", label: "Rwanda"),
      Country.new(code: "ws", label: "Samoa"),
      Country.new(code: "sm", label: "San Marino"),
      Country.new(code: "st", label: "São Tomé & Príncipe"),
      Country.new(code: "sa", label: "Saudi Arabia"),
      Country.new(code: "sn", label: "Senegal"),
      Country.new(code: "rs", label: "Serbia"),
      Country.new(code: "sc", label: "Seychelles"),
      Country.new(code: "sl", label: "Sierra Leone"),
      Country.new(code: "sg", label: "Singapore"),
      Country.new(code: "sx", label: "Sint Maarten"),
      Country.new(code: "sk", label: "Slovakia"),
      Country.new(code: "si", label: "Slovenia"),
      Country.new(code: "sb", label: "Solomon Islands"),
      Country.new(code: "so", label: "Somalia"),
      Country.new(code: "za", label: "South Africa"),
      Country.new(code: "gs", label: "South Georgia & South Sandwich Islands"),
      Country.new(code: "kr", label: "South Korea"),
      Country.new(code: "ss", label: "South Sudan"),
      Country.new(code: "es", label: "Spain"),
      Country.new(code: "lk", label: "Sri Lanka"),
      Country.new(code: "bl", label: "St. Barthélemy"),
      Country.new(code: "sh", label: "St. Helena"),
      Country.new(code: "kn", label: "St. Kitts & Nevis"),
      Country.new(code: "lc", label: "St. Lucia"),
      Country.new(code: "mf", label: "St. Martin"),
      Country.new(code: "pm", label: "St. Pierre & Miquelon"),
      Country.new(code: "vc", label: "St. Vincent & Grenadines"),
      Country.new(code: "sd", label: "Sudan"),
      Country.new(code: "sr", label: "Suriname"),
      Country.new(code: "sj", label: "Svalbard & Jan Mayen"),
      Country.new(code: "se", label: "Sweden"),
      Country.new(code: "ch", label: "Switzerland"),
      Country.new(code: "sy", label: "Syria"),
      Country.new(code: "tw", label: "Taiwan"),
      Country.new(code: "tj", label: "Tajikistan"),
      Country.new(code: "tz", label: "Tanzania"),
      Country.new(code: "th", label: "Thailand"),
      Country.new(code: "tl", label: "Timor-Leste"),
      Country.new(code: "tg", label: "Togo"),
      Country.new(code: "tk", label: "Tokelau"),
      Country.new(code: "to", label: "Tonga"),
      Country.new(code: "tt", label: "Trinidad & Tobago"),
      Country.new(code: "tn", label: "Tunisia"),
      Country.new(code: "tr", label: "Türkiye"),
      Country.new(code: "tm", label: "Turkmenistan"),
      Country.new(code: "tc", label: "Turks & Caicos Islands"),
      Country.new(code: "tv", label: "Tuvalu"),
      Country.new(code: "um", label: "U.S. Outlying Islands"),
      Country.new(code: "vi", label: "U.S. Virgin Islands"),
      Country.new(code: "ug", label: "Uganda"),
      Country.new(code: "ua", label: "Ukraine"),
      Country.new(code: "ae", label: "United Arab Emirates"),
      Country.new(code: "gb", label: "United Kingdom"),
      Country.new(code: "us", label: "United States"),
      Country.new(code: "uy", label: "Uruguay"),
      Country.new(code: "uz", label: "Uzbekistan"),
      Country.new(code: "vu", label: "Vanuatu"),
      Country.new(code: "va", label: "Vatican City"),
      Country.new(code: "ve", label: "Venezuela"),
      Country.new(code: "vn", label: "Vietnam"),
      Country.new(code: "wf", label: "Wallis & Futuna"),
      Country.new(code: "eh", label: "Western Sahara"),
      Country.new(code: "ye", label: "Yemen"),
      Country.new(code: "zm", label: "Zambia"),
      Country.new(code: "zw", label: "Zimbabwe")
    ].freeze

    def self.all = ALL
    def self.codes = ALL.map(&:code)
    def self.label(code) = ALL.find { |c| c.code == code }&.label
  end
end
